steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'runner', '.' ]
- name: 'runner'
  args:
    -  cd ${_DIR} &&
       mvn -ntp install -P${_PROFILE} -Dorg=${_ORG} -Denv=${_ENV} -Dusername=$$USERNAME -Dpassword=$$PASSWORD
  secretEnv: ['USERNAME', 'PASSWORD']

secrets:
  - kmsKeyName: projects/carrefour-288801/locations/global/keyRings/kr-apigee/cryptoKeys/k-apigee
    secretEnv:
      USERNAME: CiQAwOQGpleedzxcg/j8QK8hW0W6KvhyeHep+MPmoC3bHLciBy4SRACWEK5mDAxyEZ4vGwvDP8Kn2nI+z4DBzRa6mvLyrsMWSMsVS63x7XPJT2zlZPzRACEDNAIxj9YNvmioGJNxUAr855du
      PASSWORD: CiQAwOQGpuVan2rAscku2vX5RfI1O7YkLqNrWBKaciwbGgFxaY4SMQCWEK5m80i+3CXmg0klwiKPyb2v5r32ef4HNcyMNHn7xq8E+Y0ONGz9R3lezCieEt8=