steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'runner', '.' ]
- name: 'runner'
  args:
    -  cd ${_DIR} &&
       mvn -ntp install -P${_PROFILE} -Dorg=${_ORG} -Denv=${_ENV} -Dusername=$$USERNAME -Dpassword=$$PASSWORD
  secretEnv: ['USERNAME', 'PASSWORD']

secrets:
  - kmsKeyName: projects/carrefour-288801/locations/global/keyRings/kr-apigee/cryptoKeys/k-apigee
    secretEnv:
      USERNAME: CiQAwOQGphlIv7qb5h9x1GdzYMByYNjp+52cngHxrM7fpWlvJMoSQQCWEK5menWynShdPO1HsXQSJU6ZfK4NjnquJHUYl8B1rm7pSTiLtxTFrVdb2hU0cSsLFdqTrBDGS8Cqc0RWOhb8
      PASSWORD: CiQAwOQGpuVan2rAscku2vX5RfI1O7YkLqNrWBKaciwbGgFxaY4SMQCWEK5m80i+3CXmg0klwiKPyb2v5r32ef4HNcyMNHn7xq8E+Y0ONGz9R3lezCieEt8=